dependencies:
- graphviz
- pip:    
    - dataclasses
    - CommonMark
    - pyyaml
    - ipython
    - nbconvert
    - hypothesis
    - graphviz
    - https://github.com/deathbeds/importnb
    - https://github.com/deathbeds/sweet