dependencies:
- graphviz
- pip:    
    - dataclasses
    - CommonMark
    - pyyaml
    - ipython
    - nbconvert
    - hypothesis
    - graphviz
    - git+https://github.com/deathbeds/importnb
    - git+https://github.com/deathbeds/sweet