dependencies:
- graphviz
- pip:
    - dataclasses
    - CommonMark
    - pyyaml
    - ipython
    - nbconvert
    - hypothesis
    - graphviz
    - importnb
    # - git+https://github.com/deathbeds/sweet
